export const blogsData = [
  {
    id: 1,
    title: "html",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, ratione. Aut hic totam at eligendi molestias enim temporibus minus iure aperiam repudiandae vitae, quam magnam quo fugit provident blanditiis obcaecati magni velit! Amet velit nesciunt illo cupiditate ducimus quas totam repellendus! Ut cum optio illo adipisci atque similique blanditiis praesentium, sed quam illum pariatur consequuntur nisi voluptas possimus quos molestias repellendus at placeat consectetur esse laudantium? Officiis, in totam sint dolorem consectetur corrupti ipsam tenetur, assumenda, pariatur magni incidunt odit soluta fugit quae id ab neque voluptatem non quisquam libero accusantium quod aperiam nobis! Ut porro quidem laudantium consectetur libero, aliquam impedit omnis obcaecati sequi magni, maiores, labore nihil iste. Delectus nesciunt similique eligendi, ullam libero deleniti corrupti! Quae voluptatem vero est suscipit et! Officiis unde est explicabo, ipsum quis non odit earum quibusdam eum, praesentium illo, accusamus ratione. Numquam perferendis ex delectus quae optio illo, temporibus animi impedit esse."
  },
  {
    id: 2,
    title: "css",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, ratione. Aut hic totam at eligendi molestias enim temporibus minus iure aperiam repudiandae vitae, quam magnam quo fugit provident blanditiis obcaecati magni velit! Amet velit nesciunt illo cupiditate ducimus quas totam repellendus! Ut cum optio illo adipisci atque similique blanditiis praesentium, sed quam illum pariatur consequuntur nisi voluptas possimus quos molestias repellendus at placeat consectetur esse laudantium? Officiis, in totam sint dolorem consectetur corrupti ipsam tenetur, assumenda, pariatur magni incidunt odit soluta fugit quae id ab neque voluptatem non quisquam libero accusantium quod aperiam nobis! Ut porro quidem laudantium consectetur libero, aliquam impedit omnis obcaecati sequi magni, maiores, labore nihil iste. Delectus nesciunt similique eligendi, ullam libero deleniti corrupti! Quae voluptatem vero est suscipit et! Officiis unde est explicabo, ipsum quis non odit earum quibusdam eum, praesentium illo, accusamus ratione. Numquam perferendis ex delectus quae optio illo, temporibus animi impedit esse."
  },
  {
    id: 3,
    title: "bootstrap",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, ratione. Aut hic totam at eligendi molestias enim temporibus minus iure aperiam repudiandae vitae, quam magnam quo fugit provident blanditiis obcaecati magni velit! Amet velit nesciunt illo cupiditate ducimus quas totam repellendus! Ut cum optio illo adipisci atque similique blanditiis praesentium, sed quam illum pariatur consequuntur nisi voluptas possimus quos molestias repellendus at placeat consectetur esse laudantium? Officiis, in totam sint dolorem consectetur corrupti ipsam tenetur, assumenda, pariatur magni incidunt odit soluta fugit quae id ab neque voluptatem non quisquam libero accusantium quod aperiam nobis! Ut porro quidem laudantium consectetur libero, aliquam impedit omnis obcaecati sequi magni, maiores, labore nihil iste. Delectus nesciunt similique eligendi, ullam libero deleniti corrupti! Quae voluptatem vero est suscipit et! Officiis unde est explicabo, ipsum quis non odit earum quibusdam eum, praesentium illo, accusamus ratione. Numquam perferendis ex delectus quae optio illo, temporibus animi impedit esse."
  },
  {
    id: 4,
    title: "javascript",
    body: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint, ratione. Aut hic totam at eligendi molestias enim temporibus minus iure aperiam repudiandae vitae, quam magnam quo fugit provident blanditiis obcaecati magni velit! Amet velit nesciunt illo cupiditate ducimus quas totam repellendus! Ut cum optio illo adipisci atque similique blanditiis praesentium, sed quam illum pariatur consequuntur nisi voluptas possimus quos molestias repellendus at placeat consectetur esse laudantium? Officiis, in totam sint dolorem consectetur corrupti ipsam tenetur, assumenda, pariatur magni incidunt odit soluta fugit quae id ab neque voluptatem non quisquam libero accusantium quod aperiam nobis! Ut porro quidem laudantium consectetur libero, aliquam impedit omnis obcaecati sequi magni, maiores, labore nihil iste. Delectus nesciunt similique eligendi, ullam libero deleniti corrupti! Quae voluptatem vero est suscipit et! Officiis unde est explicabo, ipsum quis non odit earum quibusdam eum, praesentium illo, accusamus ratione. Numquam perferendis ex delectus quae optio illo, temporibus animi impedit esse."
  },
]